//---- POKEMON ----

//Create one
POST http://localhost:3000/pokemon
Content-Type: application/json

{
	"name": "pikachu",
	"id": 25,
	"damage": 50
}

###
// Read (getting all)
GET http://localhost:3000/pokemon

###
// Read (getting only caught Pokemon)
GET http://localhost:3000/pokemon/caught

###
// Read (getting one by ID). Please change the ID part accordingly
GET http://localhost:3000/pokemon/5ec2dc69e2fb6c19d1ecc8f8

###
// Read (getting one by name). Please change the name in the request payload accordingly
GET http://localhost:3000/pokemon
Content-Type: application/json

{
	"name": "pikachu"
}

###
// Update one. Please change the ID part accordingly
PATCH http://localhost:3000/pokemon/5ed3f96167e4021568244e9d
Content-Type: application/json

{
	"caught": true
}

###
// Delete one. Please change the ID part accordingly
DELETE http://localhost:3000/pokemon/5ed3f3e9b69c5d604d8ab823



//---- AUTHENTICATION ----

###
//Create one (registration)
POST http://localhost:3000/register
Content-Type: application/json

{
	"name": "Iana",
	"email": "mansuedei@gmail.com",
	"password": "qwerty"
}

###
// Read (getting all)
GET http://localhost:3000/users

###
// Delete one. Please change the ID part accordingly
DELETE http://localhost:3000/5ed422c1f9c02b7b753c2d54